[package]
name = "soupy"
version = "0.1.1"
edition = "2021"
description = "A library for parsing and querying like BeautifulSoup."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hankjordan/soupy"

[features]
default = ["regex", "lenient"]
regex = ["dep:regex"]
lenient = ["dep:scraper"]

[dependencies]
nom = "7.1"
regex = { version = "1.9", optional = true }
scraper = { version = "0.18", optional = true }
